### ISSUE TITLE
[Controller] Implement `after_action`

### ISSUE THREAD

**Issue by rsamoilov** [rage-rb/rage#19]
Implement `after_action`, that allows to register a callback to be executed after a successful action.
You can use the current implementation of `before_action` as a reference.

Make sure to thoroughly cover the change with tests and add documentation using [YARD](https://rubydoc.info/gems/yard/file/docs/Tags.md). Also, please document the differences between this implementation and the Rails implementation.

💡 The change should be made in [rage/controller/api.rb](https://github.com/rage-rb/rage/blob/master/lib/rage/controller/api.rb).
💡 Use `yard server --reload` to verify your documentation changes.

❗ Do not hesitate to use [benchmark-ips](https://github.com/evanphx/benchmark-ips) whenever there are different implementation options. When working on gems, performance is much more important than readability.

***Please comment on this issue or assign to yourself in case you have started to work on it.***

**Comment by heysyam99** [comment]
@rsamoilov can i pick this one!

**Comment by rsamoilov** [comment]
Hey @heysyam99 , are you still working on this?

**Comment by heysyam99** [comment]
Hey @rsamoilov, sorry for taking up so much time. I'm a bit packed with other stuff right now and will drop from this issue

**Comment by debobrototalukder** [comment]
Hello @rsamoilov, could I be assigned to this task if it's still available?

**Comment by debobrototalukder** [comment]
In this case, please assign it to me.

**Comment by rsamoilov** [comment]
hey @debobrototalukder , are you still working on this issue?

**Comment by debobrototalukder** [comment]
Unfortunately, I'm having a hard time set up rage in my mac M2 machine. I don't think I will be able to complete it.
