### ISSUE TITLE
[Controller] Allow to access request headers

### ISSUE THREAD

**Issue by rsamoilov** [rage-rb/rage#3]
Expose a `request` object with the `headers` property to allow users to access request headers. Users should be able to access headers data by both meta-variable names (e.g. `HTTP_CONTENT_TYPE`) and original names (e.g. `Content-Type`).

Example:

```ruby
request.headers["Content-Type"]
```

Make sure to thoroughly cover the change with tests and add documentation using [YARD](https://rubydoc.info/gems/yard/file/docs/Tags.md). Also, please don't use the `Rack::Request` object.

💡 The change should be made in [rage/controller/api.rb](https://github.com/rage-rb/rage/blob/master/lib/rage/controller/api.rb).
💡 Use `yard server --reload` to verify your documentation changes.

❗ Do not hesitate to use [benchmark-ips](https://github.com/evanphx/benchmark-ips) whenever there are different implementation options. When working on gems, performance is much more important than readability.

***Please comment on this issue or assign to yourself in case you have started to work on it.***

**Comment by heysyam99** [comment]
Hey, @rsamoilov just wondering if the request object is already in place because i don't see any request implementation yet

**Comment by rsamoilov** [comment]
Hey @heysyam99 , no, there's no implementation of the request object yet.
