### ISSUE TITLE
Question: Would it be expected that a web server (such as Puma or Unicorn) would not be needed?

### ISSUE THREAD

**Issue by blitline-dev** [rage-rb/rage#45]
What are the expected deployment scenarios for this? 

How would you configure nginx to work with this (for example: how does nginx thread configuration change in relation to non-blocking fibers)

**Comment by rsamoilov** [comment]
hey @blitline-dev 

Right, Puma or Unicorn is not needed with this gem. It's already bundled with an app server.

As for nginx, the fact that fibers are paused and resumed later is unknown to nginx. To nginx, it's still the same request/response cycle. So, I don't think any configuration changes are needed. The only thing you might want to do is revise the [worker_connections](https://nginx.org/en/docs/ngx_core_module.html#worker_connections) option.

**Comment by rsamoilov** [comment]
It is hard to tell if you are asking about all the features listed in the README. However, I plan on making a first production-ready release in early January.
