### ISSUE TITLE
Install requirements missing - Should indicate 3.1 is required

### ISSUE THREAD

**Issue by blitline-dev** [rage-rb/rage#46]
Tried to install using ruby 3.0 and it WILL install, but installs OLD version of gem, with broken  `rage new my_app` feature.

There appears to be a problem using the built in `rage new my_app` feature.

Repo Steps:

1. docker run -it ruby:3.0-buster bash
2. gem install rage-rb
3. rage new my_app
4. cd my_app
5. cat Gemfile

Expected output:
```
source "https://rubygems.org"

gem "rage-rb"

# Build JSON APIs with ease
# gem "alba"
```

Actual output:
```
source "https://rubygems.org"

gem "rage"

# Build JSON APIs with ease
# gem "alba"
```

NOTE:
gem "rage" is a Video Game support gem for using ruby to build video games and is drastically different than this rage gem :)

CONCLUSION:
Figured out from gem spec rage-rb requires Ruby 3.1 or better. Should be documented on Homepage probably.

**Comment by blitline-dev** [comment]
Answered my own question. It appears when you generate a project using rage-rb it creates a Gemfile for you with

**Comment by blitline-dev** [comment]
Or, for some reason from a clean machine,  "gem install rage-rb" doesn't install the latest version on ruby-gems.

**Comment by rsamoilov** [comment]
Thanks for the feedback! I will update the README.

**Comment by rsamoilov** [comment]
done 🙂
