### ISSUE TITLE
[Controller] Implement block version of `before_action`

### ISSUE THREAD

**Issue by rsamoilov** [rage-rb/rage#6]
Currently, `before_action` only allows method names as a handler. Amend the current implementation to also allow the following form:

```ruby
before_action do
  Photo.first
end
```

You can use the current implementation of `rescue_from` as a reference.

Make sure to thoroughly cover the change with tests and add documentation using [YARD](https://rubydoc.info/gems/yard/file/docs/Tags.md). Also, please document the differences between this implementation and the Rails implementation.

💡 The change should be made in [rage/controller/api.rb](https://github.com/rage-rb/rage/blob/master/lib/rage/controller/api.rb).
💡 Use `yard server --reload` to verify your documentation changes.

❗ Do not hesitate to use [benchmark-ips](https://github.com/evanphx/benchmark-ips) whenever there are different implementation options. When working on gems, performance is much more important than readability.

**Comment by heysyam99** [comment]
Hey @rsamoilov. I would like to pickup this issue

**Comment by heysyam99** [comment]
I need help to push the publish the branch. Getting this error

```
remote: Permission to rage-rb/rage.git denied to heysyam99.
fatal: unable to access 'https://github.com/rage-rb/rage.git/': The requested URL returned error: 403
```

**Comment by rsamoilov** [comment]
Hey @heysyam99 

Go for it!

You will need to create a fork in order to make the changes.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by heysyam99** [comment]
Thanks @rsamoilov. Will give it a try later

**Comment by heysyam99** [comment]
This is the [PR](https://github.com/rage-rb/rage/pull/8) for this issue. @rsamoilov
