### ISSUE TITLE
Memory leak + massive speed down issue

### ISSUE THREAD

**Issue by nikki-dev-s** [rage-rb/rage#98]
I want to report about critical-ish issue with your project. Everything works fine on version 1.0. If you install at least >1.5, EVERYTHING is broken. The problem is - for each request there is a LARGE memory leak, and throughput itself is heavely crippled. I don't know how you didn't noticed it and I don't know what is causing it. The screens will say everything. 
![Screenshot from 2024-08-14 18-05-07](https://github.com/user-attachments/assets/980ffddd-f310-4b29-b356-b441074dbb08)
![Screenshot from 2024-08-14 18-05-21](https://github.com/user-attachments/assets/a76b1984-b62b-401c-8295-d952ac67f678)
![Screenshot from 2024-08-14 18-06-02](https://github.com/user-attachments/assets/a421c32f-541b-4fbb-9a32-cb22806805e1)
![Screenshot from 2024-08-14 18-06-08](https://github.com/user-attachments/assets/0248862b-c2cb-476e-9b3d-43799be34bf7)
The first two are made with v. 1.5.
The second pair is when v.1.0 is used.

**Comment by nikki-dev-s** [comment]
I didn't change anything else. This is not original rails template, but i've just modified it to send plain text response instead of database query. I've used it to be sure it wasn't me who fucked up. The same problem is in my current project. When I downgrade to v.1.0 speeds increases massively..

**Comment by nikki-dev-s** [comment]
The version of ruby I'm using is 3.3.4 + YJIT + jemalloc if that matters. Maybe it's YJIT problem, but i'm 100% sure its an error in your code somewhere. Maybe it does not kill the fibers or something?

**Comment by rsamoilov** [comment]
Hey @nikki-dev-s ,

Thank you for opening the issue!

I agree this is likely an error somewhere in Rage, but I'm having difficulties trying to pinpoint it.

I assume you are running a Rails app with Rage? Could you please confirm you still see the issue with Rage 1.5.0 and **both** `RAGE_ENV` and `RAILS_ENV` environment variables set to `production`?

**Comment by nikki-dev-s** [comment]
> Hey @nikki-dev-s ,
> 
> Thank you for opening the issue!
> 
> I agree this is likely an error somewhere in Rage, but I'm having difficulties trying to pinpoint it.
> 
> I assume you are running a Rails app with Rage? Could you please confirm you still see the issue with Rage 1.5.0 and **both** `RAGE_ENV` and `RAILS_ENV` environment variables set to `production`?

Yes, the issue still exists when both envs are used. I assume, i should always set them BOTH to production by the way?

**Comment by rsamoilov** [comment]
> I assume, i should always set them BOTH to production by the way?

No, you should only need one. It works well if you set `RAILS_ENV`. But there's currently a bug where if you set only `RAGE_ENV` or use the `-e` option with `rage s`, Rails will still think it's running in development.

> Yes, the issue still exists when both envs are used. Yes, i've tested with clean rage+rails integration.

I can't seem to be able to reproduce the issue. I tried modifying the `/bookings` endpoint in [the test app](https://github.com/rage-rb/rails-integration-app) to send plain text response instead of the database query. I also checked the results of the [TFB benchmarks](https://github.com/TechEmpower/FrameworkBenchmarks), but it all looks OK.

Could you please share your test app (with the Gemfile.lock) and steps to reproduce?

**Comment by rsamoilov** [comment]
> > Also i have another question/request, i may ask about here i guess. I wanted to integrate Avo admin panel to my app, and everything works fine, except the styles and .js, which should load from /public are not loaded. They 404.
> 
> Nice! Are you using `Rage.multi_application` for this? I'll add the ability to serve public assets this week.

Until then, you can serve your static assets using the `Rack::Static` middleware (it's part of Rack, so no additional gems are required):

```ruby
Rage.configure do
  config.middleware.use Rack::Static, urls: [""], root: "public", cascade: true
end
```

**Comment by nikki-dev-s** [comment]
Okay, i did additional testing, and it is the rails v7.2 is causing this problem.

**Comment by rsamoilov** [comment]
wow, I can see it now. Looking into whether it's something we can fix on our end.

**Comment by rsamoilov** [comment]
OK, I created https://github.com/rails/rails/issues/52617.

I will continue working on Rails 7.2 compatibility. And I will notify you once Rage can serve public assets. 

Thanks again for opening the issue!
